import { type WaiverRecord } from "@/lib/waiver-status";

export const MOCK_WAIVERS: WaiverRecord[] = [
  {
    id: "WA-2201",
    projectId: "proj-north-campus",
    projectName: "North Campus Expansion",
    contractorId: "contractor-summit-concrete",
    contractorName: "Summit Concrete",
    payAppNumber: 18,
    waiverType: "conditional_progress",
    amount: 48250,
    status: "missing",
    updatedAt: "2026-02-05",
  },
  {
    id: "WA-2202",
    projectId: "proj-riverfront-tower",
    projectName: "Riverfront Tower",
    contractorId: "contractor-prime-steel",
    contractorName: "Prime Steel",
    payAppNumber: 21,
    waiverType: "unconditional_progress",
    amount: 112400,
    status: "requested",
    updatedAt: "2026-02-06",
  },
  {
    id: "WA-2203",
    projectId: "proj-civic-garage",
    projectName: "Civic Center Garage",
    contractorId: "contractor-delta-electric",
    contractorName: "Delta Electric",
    payAppNumber: 12,
    waiverType: "conditional_final",
    amount: 28750,
    status: "uploaded",
    subStatus: "needs_review",
    updatedAt: "2026-02-04",
  },
  {
    id: "WA-2204",
    projectId: "proj-harborview-labs",
    projectName: "Harborview Labs",
    contractorId: "contractor-skyline-masonry",
    contractorName: "Skyline Masonry",
    payAppNumber: 9,
    waiverType: "conditional_progress",
    amount: 19300,
    status: "approved",
    updatedAt: "2026-02-03",
  },
  {
    id: "WA-2205",
    projectId: "proj-riverfront-tower",
    projectName: "Riverfront Tower",
    contractorId: "contractor-north-plumbing",
    contractorName: "North Plumbing",
    payAppNumber: 21,
    waiverType: "unconditional_progress",
    amount: 36400,
    status: "uploaded",
    updatedAt: "2026-02-06",
  },
  {
    id: "WA-2206",
    projectId: "proj-north-campus",
    projectName: "North Campus Expansion",
    contractorId: "contractor-apex-glass",
    contractorName: "Apex Glass",
    payAppNumber: 18,
    waiverType: "conditional_progress",
    amount: 15800,
    status: "requested",
    updatedAt: "2026-02-05",
  },
  {
    id: "WA-2207",
    projectId: "proj-civic-garage",
    projectName: "Civic Center Garage",
    contractorId: "contractor-prime-steel",
    contractorName: "Prime Steel",
    payAppNumber: 12,
    waiverType: "unconditional_final",
    amount: 72500,
    status: "approved",
    updatedAt: "2026-02-06",
  },
  {
    id: "WA-2208",
    projectId: "proj-harborview-labs",
    projectName: "Harborview Labs",
    contractorId: "contractor-horizon-roofing",
    contractorName: "Horizon Roofing",
    payAppNumber: 9,
    waiverType: "conditional_progress",
    amount: 22450,
    status: "missing",
    updatedAt: "2026-02-02",
  },
  {
    id: "WA-2209",
    projectId: "proj-lakeview-clinic",
    projectName: "Lakeview Clinic",
    contractorId: "contractor-ironline-steel",
    contractorName: "Ironline Steel",
    payAppNumber: 6,
    waiverType: "conditional_progress",
    amount: 51200,
    status: "requested",
    subStatus: "rejected",
    updatedAt: "2026-02-01",
  },
  {
    id: "WA-2210",
    projectId: "proj-summit-arena",
    projectName: "Summit Arena Renovation",
    contractorId: "contractor-copper-ridge-plumbing",
    contractorName: "Copper Ridge Plumbing",
    payAppNumber: 4,
    waiverType: "conditional_final",
    amount: 38900,
    status: "uploaded",
    subStatus: "needs_review",
    updatedAt: "2026-02-06",
  },
];
