import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import TopNav from "@/components/top-nav";
import { createClient } from "@/lib/supabase/server";
import ModeProvider from "@/components/mode-provider";
import { hasModuleAccess } from "@/lib/access/modules";
import { getRequiredModuleForPath } from "@/lib/access/route-guard";
import { getCompanyForUser } from "@/lib/company/getCompanyForUser";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers();
  const currentPath = headerList.get("x-pathname") ?? "/";
  const isRequestAccess = currentPath.startsWith("/request-access");
  const isUpgradePage = currentPath === "/upgrade" || currentPath.startsWith("/upgrade/");
  const isAuthPage = currentPath === "/login" || currentPath.startsWith("/login/");

  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();
  const userId = data.user?.id ?? null;
  const company = userId ? await getCompanyForUser() : null;
  const hasWaiverdesk = hasModuleAccess(company, "waiverdesk");
  const hasPm = hasModuleAccess(company, "pm");
  let activeMode: "waiverdesk" | "pm" | "bidding" = "bidding";

  if (userId) {
    const { data: profile } = await supabase
      .from("profiles")
      .select("active_mode")
      .eq("id", userId)
      .single();

    if (profile?.active_mode === "waiverdesk" && hasWaiverdesk) activeMode = "waiverdesk";
    else if (profile?.active_mode === "pm" && hasPm) activeMode = "pm";
    else activeMode = "bidding";
  }

  const requiredModule = getRequiredModuleForPath(currentPath);
  if (
    userId &&
    requiredModule &&
    !isUpgradePage &&
    !isRequestAccess &&
    !isAuthPage &&
    !hasModuleAccess(company, requiredModule)
  ) {
    redirect(`/upgrade?module=${requiredModule}`);
  }

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spaceGrotesk.variable} antialiased`}
      >
        <ModeProvider initialMode={activeMode}>
          <div className="min-h-screen bg-white text-black">
            <TopNav />
            <div className="min-w-0">{children}</div>
          </div>
        </ModeProvider>
      </body>
    </html>
  );
}
