import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import TopNav from "@/components/top-nav";
import { createClient } from "@/lib/supabase/server";
import ModeProvider from "@/components/mode-provider";
import { canAccessPm } from "@/lib/pm-access";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers();
  const currentPath = headerList.get("x-pathname") ?? "/";
  const isWaiverPath = currentPath.startsWith("/waiverdesk");
  const isRequestAccess = currentPath.startsWith("/request-access");

  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();
  const userId = data.user?.id ?? null;
  let activeMode: "waiverdesk" | "pm" = "waiverdesk";

  if (userId) {
    const { data: profile } = await supabase
      .from("profiles")
      .select("active_mode")
      .eq("id", userId)
      .single();
    if (profile?.active_mode === "pm") {
      activeMode = "pm";
    }
  }

  const isAllowedPm = canAccessPm(data.user?.email);
  if (!isWaiverPath && !isRequestAccess && !isAllowedPm) {
    redirect("/request-access");
  }

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spaceGrotesk.variable} antialiased`}
      >
        <ModeProvider initialMode={activeMode}>
          <div className="min-h-screen bg-white text-black">
            <TopNav />
            <div className="min-w-0">{children}</div>
          </div>
        </ModeProvider>
      </body>
    </html>
  );
}
