import type { ScheduleTask } from "@/lib/tasks/analytics";

export const INITIAL_SCHEDULE_TASKS: ScheduleTask[] = [
  {
    id: "task-1",
    name: "Mobilization + temp utilities",
    owner: "GC",
    phase: "Precon",
    start: "2026-02-03",
    end: "2026-02-07",
    progress: 100,
    status: "on-track",
  },
  {
    id: "task-2",
    name: "Foundations + underground",
    owner: "Site/Civil",
    phase: "Structure",
    start: "2026-02-10",
    end: "2026-02-20",
    progress: 45,
    status: "at-risk",
  },
  {
    id: "task-3",
    name: "Steel + deck install",
    owner: "Steel",
    phase: "Structure",
    start: "2026-03-05",
    end: "2026-04-12",
    progress: 15,
    status: "on-track",
  },
  {
    id: "task-4",
    name: "Exterior envelope",
    owner: "Envelope",
    phase: "Envelope",
    start: "2026-04-01",
    end: "2026-05-10",
    progress: 0,
    status: "off-track",
  },
  {
    id: "task-5",
    name: "MEP rough-in",
    owner: "MEP",
    phase: "Interiors",
    start: "2026-04-15",
    end: "2026-05-30",
    progress: 0,
    status: "on-track",
  },
  {
    id: "task-6",
    name: "Inspections + closeout",
    owner: "GC",
    phase: "Closeout",
    start: "2026-06-03",
    end: "2026-06-14",
    progress: 0,
    status: "on-track",
  },
];
