import { ProcurementItem } from "./types";

export function mockProcurementItems(projectId: string): ProcurementItem[] {
  const safeProjectId = projectId?.trim() || "project";
  const prefix = safeProjectId.replace(/[^a-zA-Z0-9_-]/g, "");
  return [
    {
      id: `${prefix}-proc-rtu-01`,
      project_id: projectId,
      item_name: "Rooftop unit (RTU-4)",
      vendor_name: "CoolAir Systems",
      status: "in_production",
      approved_date: "2026-01-12",
      ordered_date: "2026-01-18",
      lead_time_days: 56,
      need_by_date: "2026-03-05",
      expected_delivery_date: "2026-03-20",
      actual_delivery_date: null,
      po_number: "PO-10441",
      notes: "Vendor pushed ship date by 2 weeks.",
      received_by: "Taylor Brooks",
      received_date: null,
      qc_status: null,
      qc_notes: null,
      qc_match_submittals: null,
      notes_history: [
        { note: "Vendor pushed ship date by 2 weeks.", created_at: "2026-02-02T09:15:00.000Z" },
      ],
      created_at: "2026-01-05T10:00:00.000Z",
      updated_at: "2026-02-02T09:15:00.000Z",
      archived_at: null,
    },
    {
      id: `${prefix}-proc-glass-02`,
      project_id: projectId,
      item_name: "Curtain wall glass package",
      vendor_name: "Pinnacle Glazing",
      status: "shipped",
      approved_date: "2025-12-22",
      ordered_date: "2026-01-05",
      lead_time_days: 70,
      need_by_date: "2026-03-20",
      expected_delivery_date: "2026-03-14",
      actual_delivery_date: null,
      po_number: "PO-10412",
      notes: "Mockup approved. Confirm delivery dock schedule.",
      received_by: null,
      received_date: null,
      qc_status: null,
      qc_notes: null,
      qc_match_submittals: null,
      notes_history: [
        { note: "Mockup approved. Confirm delivery dock schedule.", created_at: "2026-02-01T16:42:00.000Z" },
      ],
      created_at: "2025-12-20T14:30:00.000Z",
      updated_at: "2026-02-01T16:42:00.000Z",
      archived_at: null,
    },
    {
      id: `${prefix}-proc-elev-03`,
      project_id: projectId,
      item_name: "Passenger elevator (2-stop)",
      vendor_name: "Summit Elevation",
      status: "approved",
      approved_date: "2026-01-28",
      ordered_date: null,
      lead_time_days: 90,
      need_by_date: "2026-05-01",
      expected_delivery_date: null,
      actual_delivery_date: null,
      po_number: null,
      notes: "Awaiting release to fabrication.",
      received_by: null,
      received_date: null,
      qc_status: null,
      qc_notes: null,
      qc_match_submittals: null,
      notes_history: [
        { note: "Awaiting release to fabrication.", created_at: "2026-01-28T12:00:00.000Z" },
      ],
      created_at: "2026-01-10T08:00:00.000Z",
      updated_at: "2026-01-28T12:00:00.000Z",
      archived_at: null,
    },
    {
      id: `${prefix}-proc-panels-04`,
      project_id: projectId,
      item_name: "Switchgear + electrical panels",
      vendor_name: "Northline Electric",
      status: "ordered",
      approved_date: "2026-01-07",
      ordered_date: "2026-01-09",
      lead_time_days: 45,
      need_by_date: "2026-03-01",
      expected_delivery_date: "2026-02-28",
      actual_delivery_date: null,
      po_number: "PO-10388",
      notes: "Tracking #S8742 issued.",
      received_by: null,
      received_date: null,
      qc_status: null,
      qc_notes: null,
      qc_match_submittals: null,
      notes_history: [
        { note: "Tracking #S8742 issued.", created_at: "2026-01-09T15:45:00.000Z" },
      ],
      created_at: "2026-01-07T09:00:00.000Z",
      updated_at: "2026-01-09T15:45:00.000Z",
      archived_at: null,
    },
    {
      id: `${prefix}-proc-doors-05`,
      project_id: projectId,
      item_name: "Exterior doors + hardware set",
      vendor_name: "Holloway Door Co.",
      status: "delivered",
      approved_date: "2025-12-15",
      ordered_date: "2025-12-18",
      lead_time_days: 30,
      need_by_date: "2026-02-10",
      expected_delivery_date: "2026-02-08",
      actual_delivery_date: "2026-02-08",
      po_number: "PO-10301",
      notes: "Stored in laydown area.",
      received_by: "Morgan Lee",
      received_date: "2026-02-08",
      qc_status: "pass",
      qc_notes: "Checked for damage; all hardware accounted for.",
      qc_match_submittals: true,
      notes_history: [
        { note: "Stored in laydown area.", created_at: "2026-02-08T11:30:00.000Z" },
      ],
      created_at: "2025-12-12T10:00:00.000Z",
      updated_at: "2026-02-08T11:30:00.000Z",
      archived_at: null,
    },
    {
      id: `${prefix}-proc-tile-06`,
      project_id: projectId,
      item_name: "Lobby porcelain tile",
      vendor_name: "Stone + Tile Collective",
      status: "awaiting_approval",
      approved_date: null,
      ordered_date: null,
      lead_time_days: 21,
      need_by_date: "2026-03-15",
      expected_delivery_date: null,
      actual_delivery_date: null,
      po_number: null,
      notes: "Awaiting designer selection.",
      received_by: null,
      received_date: null,
      qc_status: null,
      qc_notes: null,
      qc_match_submittals: null,
      notes_history: [
        { note: "Awaiting designer selection.", created_at: "2026-01-18T13:20:00.000Z" },
      ],
      created_at: "2026-01-18T13:20:00.000Z",
      updated_at: "2026-01-18T13:20:00.000Z",
      archived_at: null,
    },
  ];
}
